BEGIN TRANSACTION;
CREATE TABLE "IKBFU_2_KB" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Subject`	TEXT,
	`StartTime`	TEXT,
	`Room`	TEXT,
	`Professor`	TEXT
);
INSERT INTO `IKBFU_2_KB` VALUES (2,'CVFT','12:00','205','--');
INSERT INTO `IKBFU_2_KB` VALUES (4,'Math','10:10','205','Aleshnikova');
COMMIT;
